<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
           xmlns:ct="http://www.decisiv.net/platform_api/0.3-beta/Case/CaseTypes"
           xmlns:s="http://www.decisiv.net/platform_api/0.3-beta/Case/Salesman"
           xmlns:e="http://www.decisiv.net/platform_api/0.3-beta/Case/EstimateItemPartResponse"
           targetNamespace="http://www.decisiv.net/platform_api/0.3-beta/Case/EstimateItemPartResponse">
  <xs:import namespace="http://www.decisiv.net/platform_api/0.3-beta/Case/CaseTypes"
             schemaLocation="CaseTypes.xsd"/>
  <xs:import namespace="http://www.decisiv.net/platform_api/0.3-beta/Case/Salesman"
    schemaLocation="Salesman.xsd"/>
  <xs:element name="part" type="e:EstimateItemPart"/>
  <xs:element name="parts">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="part" type="e:EstimateItemPart" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="EstimateItemPart">
    <xs:all>
      <xs:element name="id" type="xs:string"/>
      <xs:element name="URL" type="xs:string"/>
      <xs:element name="itemURL" type="xs:string"/>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="partNumber" type="xs:string"/>
      <xs:element name="quantity" type="xs:decimal"/>
      <xs:element name="quantityShipped" type="xs:integer"/>
      <xs:element name="quantityBackordered" type="xs:integer"/>
      <xs:element name="unitPrice" type="ct:Currency"/>
      <xs:element name="coreQuantity" type="xs:decimal"/>
      <xs:element name="unitCorePrice" type="ct:Currency"/>
      <xs:element name="totalPrice" type="ct:Currency"/>
      <xs:element name="salesman" type="s:Salesman" nillable="true" minOccurs="0"/>
      <xs:element name="source" type="xs:string"/>
      <xs:element name="createdAt" type="xs:dateTime"/>
      <xs:element name="updatedAt" type="xs:dateTime"/>
    </xs:all>
  </xs:complexType>
</xs:schema>
