<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
           xmlns:ct="http://www.decisiv.net/platform_api/0.3-beta/Case/CaseTypes"
           xmlns:s="http://www.decisiv.net/platform_api/0.3-beta/Case/Salesman"
           xmlns:g="http://www.decisiv.net/platform_api/0.2/Case/GroupedUser"
           xmlns:eit="http://www.decisiv.net/platform_api/0.2/Case/EstimateItemTypes"
           xmlns:vmrs="http://www.decisiv.net/platform_api/0.2/Case/VMRS"
           xmlns:ac="http://www.decisiv.net/platform_api/0.2/Case/AdditionalCharges"
           xmlns:e="http://www.decisiv.net/platform_api/0.3-beta/Case/EstimateItemResponse"
           xmlns:eip="http://www.decisiv.net/platform_api/0.3-beta/Case/EstimateItemPartResponse"
           targetNamespace="http://www.decisiv.net/platform_api/0.3-beta/Case/EstimateItemResponse">
  <xs:import namespace="http://www.decisiv.net/platform_api/0.3-beta/Case/CaseTypes"
             schemaLocation="CaseTypes.xsd"/>
  <xs:import namespace="http://www.decisiv.net/platform_api/0.3-beta/Case/Salesman"
             schemaLocation="Salesman.xsd"/>
  <xs:import namespace="http://www.decisiv.net/platform_api/0.2/Case/GroupedUser"
             schemaLocation="../0.2/GroupedUser.xsd"/>
  <xs:import namespace="http://www.decisiv.net/platform_api/0.2/Case/EstimateItemTypes"
             schemaLocation="../0.2/EstimateItemTypes.xsd"/>
  <xs:import namespace="http://www.decisiv.net/platform_api/0.2/Case/VMRS"
             schemaLocation="../0.2/vmrs.xsd"/>
  <xs:import namespace="http://www.decisiv.net/platform_api/0.2/Case/AdditionalCharges"
             schemaLocation="../0.2/AdditionalCharges.xsd"/>
  <xs:import namespace="http://www.decisiv.net/platform_api/0.3-beta/Case/EstimateItemPartResponse"
             schemaLocation="EstimateItemPartResponse.xsd"/>
  <xs:element name="items">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="item" type="e:EstimateItem" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="item" type="e:EstimateItem"/>
  <xs:complexType name="EstimateItem">
    <xs:all>
      <xs:element name="id" type="xs:string"/>
      <xs:element name="URL" type="xs:string"/>
      <xs:element name="estimateURL" type="xs:string"/>
      <xs:element name="partsURL" type="xs:string"/>
      <xs:element name="code" type="xs:string"/>
      <xs:element name="name" type="xs:string" nillable="true"/>
      <xs:element name="standardOperationNotes" type="xs:string" nillable="true"/>
      <xs:element name="complaint" type="xs:string" nillable="true"/>
      <xs:element name="cause" type="xs:string" nillable="true"/>
      <xs:element name="correction" type="xs:string" nillable="true"/>
      <xs:element name="jobCode" type="xs:string" nillable="true"/>
      <xs:element name="priceCode" type="xs:string" nillable="true"/>
      <xs:element name="workStatus" type="eit:WorkStatus" nillable="true"/>
      <xs:element name="assignee" type="g:GroupedUser" nillable="true"/>
      <xs:element name="soldStatus" type="eit:SoldStatus"/>
      <xs:element name="underWarranty" type="xs:boolean" nillable="true"/>
      <xs:element name="billingClassification" type="eit:BillingClassification" minOccurs="0" nillable="true"/>
      <xs:element name="labor" type="eit:LaborDetail"/>
      <xs:element name="paint" type="eit:PaintDetail"/>
      <xs:element name="additionalCharges" nillable="true">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="charge" type="ac:AdditionalCharge" maxOccurs="unbounded" minOccurs="0"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="additionalChargesTotals" nillable="true">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="total" type="ac:AdditionalChargeTotal" maxOccurs="unbounded" minOccurs="0"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="partsTotal" type="ct:Currency"/>
      <xs:element name="coreTotal" type="ct:Currency"/>
      <xs:element name="fixedPriceTotal" type="ct:Currency" minOccurs="0"/>
      <xs:element name="total" type="ct:Currency"/>
      <xs:element name="vmrs" type="vmrs:VMRS" nillable="true"/>
      <xs:element name="createdAt" type="xs:dateTime"/>
      <xs:element name="updatedAt" type="xs:dateTime"/>
      <xs:element name="approvalGroupTag" type="xs:string" nillable="true"/>
      <xs:element name="parts" nillable="true" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="part" type="eip:EstimateItemPart" maxOccurs="unbounded" minOccurs="0"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>
</xs:schema>
