<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    xmlns:r="http://www.decisiv.net/platform_api/0.3-beta/Case/RecipientResponse"
    targetNamespace="http://www.decisiv.net/platform_api/0.3-beta/Case/RecipientResponse">
    <xs:element name="recipients">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="recipient" type="r:Recipient" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="Recipient">
        <xs:all>
          <xs:element name="id" type="xs:string"/>
          <xs:element name="URL" type="xs:string"/>
          <xs:element name="name" type="xs:string"/>
          <xs:element name="affiliation" type="r:Affiliation"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="Affiliation">
        <xs:all>
          <xs:element name="accountName" type="xs:string"/>
          <xs:element name="recipientType" type="xs:string"/>
        </xs:all>
    </xs:complexType>
</xs:schema>