<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    xmlns:r="http://www.decisiv.net/platform_api/0.1/Case/RecipientResponse"
    xmlns:s="http://www.decisiv.net/platform_api/0.1/Case/SenderResponse"
    xmlns:a="http://www.decisiv.net/platform_api/0.1/Case/AttachmentResponse"
    targetNamespace="http://www.decisiv.net/platform_api/0.1/Case/AttachmentResponse">
    <xs:import namespace="http://www.decisiv.net/platform_api/0.1/Case/RecipientResponse"
        schemaLocation="RecipientResponse.xsd"/>
    <xs:import namespace="http://www.decisiv.net/platform_api/0.1/Case/SenderResponse"
        schemaLocation="SenderResponse.xsd"/>
    <xs:element name="attachments">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="attachment" type="a:Attachment" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="attachment" type="a:Attachment"/>
    <xs:complexType name="Attachment">
        <xs:all>
            <xs:element name="URL" type="xs:string"/>
            <xs:element name="subjectURL" type="xs:string"/>
            <xs:element name="id" type="xs:string"/>
            <xs:element name="downloadURL" type="xs:string"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="filename" type="xs:string"/>
            <xs:element name="format" type="xs:string"/>
            <xs:element name="size" type="xs:int"/>
            <xs:element name="internal" type="xs:boolean"/>
            <xs:element name="createdAt" type="xs:dateTime"/>
            <xs:element name="updatedAt" type="xs:dateTime"/>
            <xs:element ref="s:sender"/>
        </xs:all>
    </xs:complexType>
</xs:schema>
