<xs:schema attributeFormDefault="unqualified"
  elementFormDefault="qualified"
  targetNamespace="http://www.decisiv.net/platform_api/0.1/Invoices/Invoice"
  xmlns:i="http://www.decisiv.net/platform_api/0.1/Invoices/Invoice"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="invoice" type="i:Invoice"/>
  <xs:element name="invoices">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="invoice" type="i:Invoice" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="type"/>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="Invoice">
    <xs:all>
      <xs:element type="xs:anyURI" name="url"/>
      <xs:element name="created-at">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:dateTime">
              <xs:attribute type="xs:string" name="type"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
      <xs:element name="customer">
        <xs:complexType>
          <xs:all>
            <xs:element type="xs:string" name="tag"/>
            <xs:element type="xs:string" name="name"/>
          </xs:all>
        </xs:complexType>
      </xs:element>
      <xs:element name="due-on" nillable="true">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:date">
              <xs:attribute type="xs:string" name="type"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
      <xs:element type="xs:string" name="id"/>
      <xs:element name="issued-at" nillable="true">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:dateTime">
              <xs:attribute type="xs:string" name="type"/>
              <xs:attribute type="xs:string" name="nil" use="optional"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
      <xs:element name="lines">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="line" minOccurs="0">
              <xs:complexType>
                <xs:all>
                  <xs:element name="connections">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="connection" maxOccurs="unbounded" minOccurs="0">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element type="xs:string" name="relationship"/>
                              <xs:element type="xs:string" name="tag"/>
                              <xs:element name="url">
                                <xs:complexType>
                                  <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                      <xs:attribute type="xs:string" name="nil" use="optional"/>
                                    </xs:extension>
                                  </xs:simpleContent>
                                </xs:complexType>
                              </xs:element>
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:sequence>
                      <xs:attribute type="xs:string" name="type"/>
                    </xs:complexType>
                  </xs:element>
                  <xs:element type="xs:string" name="description"/>
                  <xs:element name="measurement" nillable="true" minOccurs="0">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="final">
                          <xs:complexType>
                            <xs:simpleContent>
                              <xs:extension base="xs:decimal">
                                <xs:attribute type="xs:string" name="type"/>
                              </xs:extension>
                            </xs:simpleContent>
                          </xs:complexType>
                        </xs:element>
                        <xs:element name="initial">
                          <xs:complexType>
                            <xs:simpleContent>
                              <xs:extension base="xs:decimal">
                                <xs:attribute type="xs:string" name="type"/>
                              </xs:extension>
                            </xs:simpleContent>
                          </xs:complexType>
                        </xs:element>
                        <xs:element type="xs:string" name="unit"/>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                  <xs:element name="quantity">
                    <xs:complexType>
                      <xs:simpleContent>
                        <xs:extension base="xs:decimal">
                          <xs:attribute type="xs:string" name="type"/>
                        </xs:extension>
                      </xs:simpleContent>
                    </xs:complexType>
                  </xs:element>
                  <xs:element type="xs:string" name="tag"/>
                  <xs:element name="total">
                    <xs:complexType>
                      <xs:simpleContent>
                        <xs:extension base="xs:decimal">
                          <xs:attribute type="xs:string" name="type"/>
                        </xs:extension>
                      </xs:simpleContent>
                    </xs:complexType>
                  </xs:element>
                  <xs:element name="unit-price">
                    <xs:complexType>
                      <xs:simpleContent>
                        <xs:extension base="xs:decimal">
                          <xs:attribute type="xs:string" name="type"/>
                        </xs:extension>
                      </xs:simpleContent>
                    </xs:complexType>
                  </xs:element>
                  <xs:element name="unit-tax">
                    <xs:complexType>
                      <xs:simpleContent>
                        <xs:extension base="xs:decimal">
                          <xs:attribute type="xs:string" name="type"/>
                        </xs:extension>
                      </xs:simpleContent>
                    </xs:complexType>
                  </xs:element>
                  <xs:element name="vmrs" nillable="true" minOccurs="0">
                    <xs:complexType>
                      <xs:all>
                        <xs:element type="xs:string" name="code14" nillable="true"/>
                        <xs:element type="xs:string" name="code15" nillable="true"/>
                        <xs:element type="xs:string" name="code33" nillable="true"/>
                      </xs:all>
                    </xs:complexType>
                  </xs:element>
                </xs:all>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
          <xs:attribute type="xs:string" name="type"/>
        </xs:complexType>
      </xs:element>
      <xs:element type="xs:string" name="number" nillable="true"/>
      <xs:element type="xs:string" name="po-number" nillable="true"/>
      <xs:element name="total">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:decimal">
              <xs:attribute type="xs:string" name="type"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
      <xs:element name="seller">
        <xs:complexType>
          <xs:all>
            <xs:element type="xs:string" name="tag"/>
            <xs:element type="xs:string" name="name"/>
          </xs:all>
        </xs:complexType>
      </xs:element>
      <xs:element type="xs:string" name="status"/>
      <xs:element name="updated-at">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:dateTime">
              <xs:attribute type="xs:string" name="type"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>
</xs:schema>
